export default [{
        name: 'Guns and Roses',
        category: 'Rock',
        imgUrl: 'https://pbs.twimg.com/profile_images/885491686327169024/ufh03Wmg_400x400.jpg',
        info: 'Guns and Roses es una banda estadounidense de hard rock formada en Hollywood en 1985. El grupo fue fundado por Axl Rose y el guitarrista rítmico Izzy Stradlin.​',
        origin: 'Los Angeles, California, U.S.',
        yearsActive: '1985–present',
        members: 'Slash, Axl Rose, Duff McKagan, Melissa Reese, ...',
    },

    {
        name: 'Iron Maiden',
        category: 'Rock',
        imgUrl: 'https://i2.wp.com/musictrajectory.com/wp-content/uploads/2011/08/iron-maiden-run-to-the-hills-single-cover.jpg',
        info: '',
        origin: '',
        yearsActive: '',
        members: '',
    },
    {
        name: 'AC DC',
        category: 'Rock',
        imgUrl: 'https://images-na.ssl-images-amazon.com/images/I/71pC173hqVL._SL1500_.jpg',
        info: '',
        origin: '',
        yearsActive: '',
        members: '',
    },
    {
        name: 'Metallica',
        category: 'Rock',
        imgUrl: 'http://hello-georgia.com/files/news/117859639_1366089934.jpg',
        info: '',
        origin: '',
        yearsActive: '',
        members: '',
    },
    {
        name: 'Led Zeppelin',
        category: 'Rock',
        imgUrl: 'https://cps-static.rovicorp.com/3/JPG_500/MI0003/942/MI0003942580.jpg',
        info: '',
        origin: '',
        yearsActive: '',
        members: '',
    },
    {
        name: 'Eminem',
        category: 'Rap',
        imgUrl: 'http://images4.fanpop.com/image/photos/17800000/Eminem-and-D12-eminem-and-the-gang-17878613-632-713.jpg',
        info: '',
        origin: '',
        yearsActive: '',
        members: '',
    },
    {
        name: 'Porta',
        category: 'Rap',
        imgUrl: 'http://mp3.hhgroups.com/albumes/Porta-En-boca-de-tantos-31776_front.jpg',
        info: '',
        origin: '',
        yearsActive: '',
        members: '',
    },
    {
        name: 'Nach',
        category: 'Rap',
        imgUrl: 'http://www.nach.es/img/fondo_header.jpg',
        info: '',
        origin: '',
        yearsActive: '',
        members: '',
    },
    {
        name: 'Canserbero',
        category: 'Rap',
        imgUrl: 'https://i.ytimg.com/vi/U6fYdzOJEyo/maxresdefault.jpg',
        info: '',
        origin: '',
        yearsActive: '',
        members: '',
    },
    {
        name: 'The Wailers',
        category: 'Reggae',
        imgUrl: 'https://d31fr2pwly4c4s.cloudfront.net/c/6/a/1000509_0_the-wailers_1024.jpg',
        info: '',
        origin: '',
        yearsActive: '',
        members: '',
    },
    {
        name: 'Bob Marley',
        category: 'Reggae',
        imgUrl: 'https://images.fineartamerica.com/images-medium-large-5/original-painting-bob-marley-enxu-zhou.jpg',
        info: '',
        origin: '',
        yearsActive: '',
        members: '',
    },
    {
        name: 'Cultura Profética',
        category: 'Reggae',
        imgUrl: 'https://i.scdn.co/image/67303b156ab972a5aabdd10be88213163b40e8f3',
        info: '',
        origin: '',
        yearsActive: '',
        members: '',
    }
]